// packages/demo/src/counter/react/view.tsx
// export const Counter = reaxper( class extends Reaxlass {
//	
// 	reax_counter = reaxel_counter();
//	
// 	render() {
// 		const {count , setCount} = this.reax_counter;
//		
// 		return <>
// 			<p>current count : { count }</p>
// 			<button onClick = { () => setCount( count + 1 ) }>
// 				click me
// 			</button>
// 		</>;
// 	}
// } );


export const Counter = reaxper( () => {
	const {count , plus} = reaxel_counter();
	
	return <>
		<p>current count : { count }</p>
		<button onClick = { () => plus() }>
			click me
		</button>
	</>;
} );

import { reaxel_counter } from '../reaxel';
import { reaxper } from 'reaxes-react';

// packages/demo/src/counter/vue3/view.vue3.vue
<script setup>
import { ref } from 'vue3';
import { reaxel_counter } from '../reaxel';
import { reaxper } from 'reaxes-vue3';
import { observable , action } from 'mobx';

const reax_count = reaxel_counter() , {
	plus,
	minus
} = reax_count;
const obs = observable({ c : 111 });
const setObs = action(() => obs.c ++); 
</script>
<template>
	<Observer>
		<!--		<div @click = 'plus'>vue3 {{ reax_count.count }}</div>-->
		<p>vue3 count : {{ reax_count.count }}</p>
		<button @click='plus()'>plus  1</button>
		<button @click='minus()'>minus 1</button>
		
		<p @click='setObs()'>obs:{{ obs.c }}</p>
	</Observer>
</template>
