// packages/demo/src/counter/vue2/view.vue
<template>
	<div id='reaxes-demo-root'>
		<p>current count : {{ x }}</p>
		<button @click = 'setX'>
			click me
		</button>
		
		
		<p>current C : {{ c }}</p>
		<button @click = 'cClick'>
			click me
		</button>
		
		<vue-son></vue-son>
	</div>
</template>

<script>
import { reaxper } from 'reaxes-vue2';
import { reaxel_counter } from '../reaxel';
import { observer , VueClass } from 'mobx-vue';
import {  observable } from "mobx";
import vue2 from './view-2.vue';
const state = observable({
	c:222
});

const {
	plus ,
	minus ,
} = reaxel_counter();



export default observer({
	components : {
		"vue-son" : vue2,
	},
	data () {
		
		const { count } = reaxel_counter();
		return {
			x : 123,
			c : state.c,
			count
		};
	} ,
	methods : {
		setX(){
			this.x ++;
		},
		cClick(){
			state.c = state.c + 1;
			console.log(state.c);
		},
		minus ,
		plus ,
	} 
});
</script>

// packages/demo/src/counter/react/view.tsx
// export const Counter = reaxper( class extends Reaxlass {
//	
// 	reax_counter = reaxel_counter();
//	
// 	render() {
// 		const {count , setCount} = this.reax_counter;
//		
// 		return <>
// 			<p>current count : { count }</p>
// 			<button onClick = { () => setCount( count + 1 ) }>
// 				click me
// 			</button>
// 		</>;
// 	}
// } );


export const Counter = reaxper( () => {
	const {count , plus} = reaxel_counter();
	
	return <>
		<p>current count : { count }</p>
		<button onClick = { () => plus() }>
			click me
		</button>
	</>;
} );

import { reaxel_counter } from '../reaxel';
import { reaxper } from 'reaxes-react';
